sudo: required
services:
  - docker
  
  
before_install:
  - docker build -t alex3dd/react-test -f ./client/Dockerfile.dev ./client  
  
script:
  - docker run alex3dd/react-test npm test -- --coverage
  
  
after_success:   
  - docker build -t alex3dd/multi-client ./client  
  - docker build -t alex3dd/multi-nginx ./nginx
  - docker build -t alex3dd/multi-server ./server
  - docker build -t alex3dd/multi-worker ./worker
  # Before push them, log in into a docker cli
  - echo "$DOCKER_PASSWORD"|docker login -u "$DOCKER_ID" --password-stdin 
  # take those images and push them to docker hub
  - docker push alex3dd/multi-client
  - docker push alex3dd/multi-nginx 
  - docker push alex3dd/multi-server
  - docker push alex3dd/multi-worker
  

